name: Create Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Decode Keystore
        run: echo "${{ secrets.RELEASE_STORE_FILE_BASE64 }}" | base64 -d > diasync.jks

      - name: Configure signing
        env:
          RELEASE_STORE_FILE: ../diasync.jks
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: echo "Using signing config from environment variables"

      - name: Build Phone Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Build Phone Release APK
        env:
          RELEASE_STORE_FILE: ../diasync.jks
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew :app:assembleRelease

      - name: Build Wear Debug APK
        run: ./gradlew :wear:assembleDebug

      - name: Build Wear Release APK
        env:
          RELEASE_STORE_FILE: ../diasync.jks
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew :wear:assembleRelease

      - name: List APK files
        run: |
          ls -la app/build/outputs/apk/debug/
          ls -la app/build/outputs/apk/release/
          ls -la wear/build/outputs/apk/debug/
          ls -la wear/build/outputs/apk/release/

      - name: Generate release tag
        id: tag
        run: |
          RELEASE_TAG="v$(TZ='Europe/Moscow' date +'%Y.%m.%d-%H%M')"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.RELEASE_TAG }}
          release_name: "Release ${{ steps.tag.outputs.RELEASE_TAG }}"
          draft: false
          prerelease: false

      - name: Upload Phone Debug APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: diasync-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Phone Release APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: diasync-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Wear Debug APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wear/build/outputs/apk/debug/wear-debug.apk
          asset_name: diasync-wear-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Wear Release APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wear/build/outputs/apk/release/wear-release.apk
          asset_name: diasync-wear-release.apk
          asset_content_type: application/vnd.android.package-archive